language: python
python:
- '3.6'
env:
- GAE_PYTHONPATH=${HOME}/ PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_d19b78e5e2f3_key -iv $encrypted_d19b78e5e2f3_iv
  -in credentials.tar.enc -out credentials.tar -d
- pip install pytest-cov
# - if [ ! -d "${GAE_PYTHONPATH}" ]; then python scripts/fetch_gae_sdk.py $(dirname
#  "${GAE_PYTHONPATH}"); fi
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xf credentials.tar
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project capstone-class8
# - gcloud -q components update gae-python
# - pip install -r requirements.txt -t lib/
script:
- py.test -v --cov=api api/tests.py
- gcloud config set project `capstone-class8`
- gcloud compute scp . travis_service@instance-1:~/ --zone us-east1-b --recurse
- gcloud compute ssh travis_service@instance-1 --zone us-east1-b << EOF sudo apt install
  apt-transport-https ca-certificates curl software-properties-common gnupg2 curl
  -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - sudo add-apt-repository
  "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  sudo apt update sudo apt install docker-ce sudo usermod -aG docker $USER EOF
